Repository done-devs/done, pull requests merged in 2023-01, with the labels that each got.

#54 Update German translation
  i18n/de/done.ftl
Labels: enhancement

#52 Update Italian translation
  i18n/it/done.ftl
Labels: enhancement

#60 Fixed color scheme delay
  src/application/appearance.rs
  src/application/mod.rs
  src/application/setup.rs
Labels: fix

#67 Fix settings pane close button
  src/widgets/components/preferences.rs
Labels: fix

#69 Replace quick creation buttons with task details pane
  src/widgets/components/content.rs
  src/widgets/components/task_entry.rs
  src/widgets/factory/task.rs
  src/widgets/factory/task_details.rs
Labels: enhancement, fix

#74 New date pickers
  src/widgets/factory/plugin.rs
  src/widgets/factory/task_details.rs
Labels: enhancement

#76 Update local-plugin to v0.1.1
  dev.edfloreshz.Done.Plugins.json
Labels: enhancement

#77 Update dev.edfloreshz.Done.Plugins.json
  dev.edfloreshz.Done.Plugins.json
Labels: enhancement
